LogFile: true
LogToConsole: 1
MIPGap: 0.01
StoreSol: false
TimeLimit: 600
base directory: /scratch/user/s4736535/Thesis/ieee_cis_solar
instance folder: small
instance index: 0
method: -1
problem: ieee_cis_solar
threads: 12
